# Generated by Django 5.0.4 on 2024-08-07 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('django_celery_beat', '0018_improve_crontab_helptext'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Schedule Name')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                ('file_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='File name')),
            ],
            options={
                'verbose_name': 'Analytics Schedule History',
                'verbose_name_plural': 'Analytics Schedule History',
            },
        ),
        migrations.CreateModel(
            name='AnalyticOutput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connection_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Connection Name')),
                ('ftp_path', models.CharField(blank=True, max_length=100, null=True)),
                ('ftp_destination_server', models.CharField(blank=True, max_length=100, null=True)),
                ('ftp_destination_user', models.CharField(blank=True, max_length=100, null=True)),
                ('ftp_destination_password', models.CharField(blank=True, max_length=100, null=True)),
                ('ftp_destination_port', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Analytics Output Coonnection',
                'verbose_name_plural': 'Analytics Output Coonnection',
            },
        ),
        migrations.CreateModel(
            name='OdooDatabase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connection_name', models.CharField(blank=True, max_length=100, null=True)),
                ('db_url', models.URLField(blank=True, null=True, verbose_name='Database URL')),
                ('db_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Database Name')),
                ('auth_mode', models.CharField(blank=True, choices=[('credentials', 'Credentials'), ('api_key', 'API Key')], max_length=20, null=True, verbose_name='Select authentication mode')),
                ('username', models.CharField(blank=True, max_length=100, null=True, verbose_name='Username')),
                ('password', models.CharField(blank=True, max_length=100, null=True, verbose_name='Password')),
                ('api_key', models.CharField(blank=True, max_length=100, null=True, verbose_name='API Key')),
            ],
            options={
                'verbose_name': 'Database Configuration',
                'verbose_name_plural': 'Database Configuration',
            },
        ),
        migrations.CreateModel(
            name='AanlyticsSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Schedule Name')),
                ('output_plan', models.IntegerField(help_text='Please input output plan in hours')),
                ('embedded_code', models.TextField(blank=True, null=True)),
                ('periodic_task', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='django_celery_beat.periodictask')),
                ('output_detail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='analytics.analyticoutput')),
                ('select_database', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.odoodatabase')),
            ],
            options={
                'verbose_name': 'Analytics Generate Schedule',
                'verbose_name_plural': 'Analytics Generate Schedule',
            },
        ),
    ]
